### ISSUE TITLE
something confused

### ISSUE THREAD

**Issue by wangtao-humanitarian** [howl-anderson/MicroTokenizer#2]
* Micro Tokenizer for Chinese version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by wangtao-humanitarian** [comment]
请问要掌握这项目需要学习什么方面的知识点 啊

**Comment by howl-anderson** [comment]
If someone doesn't know how to learn so many tokenizers, please mail me in detail, I'd like to help.
