### ISSUE TITLE
没有基于神经网络序列标注(端到端)的吗

### ISSUE THREAD

**Issue by loveJasmine** [howl-anderson/MicroTokenizer#3]

**Comment by howl-anderson** [comment]
Sorry for the very late reply, 目前 MicroTokenizer 还没集成 End-to-End DNN based model, 不过我有一个 https://github.com/howl-anderson/PaddleTokenizer 项目使用 DNN 驱动。后续计划中，有考虑将 DNN 模型加入 MicroTokenizer
